name: test
dependencies:
  - python>=3.6,<4
  - pip
  - pip:
      - pymlconf>=1.0.0,<2.0
      - google-api-python-client>=1.7.6,<2
      - hvac>=0.7
      - pyyaml>=4.2b1
      - structlog>=18.1,<19