name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - pip:
    - alembic==1.0.10
    - apispec<2,>=1
    - blinker==1.4
    - boltons<18.1,>=18.0.1
    - cachetools<4,>=2
    - cloudpickle<2,>=1.6
    - colorama
    - dask<3,>=0.15.2
    - flake8==3.7.7
    - flake8-print==3.1.0
    - flask==1.0.3
    - flask-apispec==0.8.1
    - flask-compress==1.4.0
    - flask-cors==3.0.8
    - flask-marshmallow==0.10.1
    - google-api-python-client<2,>=1.7.6
    - google-auth>=1.16.0
    - google-cloud-storage<2,>=1.13.0
    - gunicorn==19.9.0
    - hvac<0.11,>=0.10
    - hypothesis==4.23.9
    - isort==4.3.21
    - joblib<0.13,>=0.12.5
    - marshmallow<3.1,>=3.0.0rc5
    - marshmallow-sqlalchemy==0.16.3
    - memoized-property<1.1,>=1.0.2
    - mypy>=0.701
    - notebook==5.7.8
    - numpy>=1.16.4
    - pandas<1,>=0.22.0
    - prometheus-client==0.6.0
    - pyarrow<1,>=0.15.1
    - pytest==5.0.1
    - pytest-cov==2.7.1
    - pytest-describe==0.12.0
    - pytest-env==0.6.2
    - pytest-mock==1.10.3
    - pytest-xdist==1.27.0
    - pyyaml==3.13
    - requests>=2.21.0
    - s3fs==0.1.6
    - sqlalchemy<1.4,>=1.3
    - sqlalchemy-utils==0.33.11
    - structlog<18.2,>=18.1.0
    - toolz<0.10,>=0.8.2
    - typed-ast>=1.4.2
    - webargs==5.5.3
    - werkzeug==0.16.1
    - wrapt<1.13,>=1.12.1
    - yapf==0.28.0